id = "zarcula-theme"
name = "Zarcula"
version = "0.1.2"
schema_version = 1
authors = ["Ihor Horun <igor.goroun@gmail.com>"]
description = "Darculaâ€™s sophisticated cousin, custom-built for Zed."
repository = "https://github.com/igorgoroun/zed-zarcula-theme"
