id = "zed-zarcula-theme"
name = "Zarcula"
version = "0.1.0"
schema_version = 1
authors = ["Ihor Horun"]
description = "Zarcula: Looks close to JetBrains Darcula Theme ^_^"
repository = "https://github.com/igorgoroun/zed-zarcula-theme"
