id = "zed-zarcula-theme"
name = "Zarcula"
version = "0.1.0"
schema_version = 1
authors = ["Ihor Horun"]
description = "Zarcula: Darculaâ€™s sophisticated cousin, custom-built for Zed."
repository = "https://github.com/igorgoroun/zed-zarcula-theme"
